# 服务端口
server:
  port: 8001

spring:
  # 服务名
  application:
    name: service-edu
  # 环境设置：dev、test、prod
  profiles:
    active: dev
# mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_edu?serverTimezone=GMT%2B8
    username: root
    password: qq123456
    hikari:
      connection-test-query: SELECT 1
    connection-timeout: 60000
    idle-timeout: 500000
    max-lifetime: 540000
    maximum-pool-size: 12
    minimum-idle: 10
    pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
