#服务端口号
server:
  port: 8002

spring:
  #应用名
  profiles:
    active: dev
  #应用
  application:
    name: service-oss

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      #阿里云账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM用户进行API访问或日常运维，请登录RAM控制台创建RAM用户。
      keyid: "LTAI4GFPUe9crctvhvJfiavv"
      keysecret: "5RuR6awOLSGJfWOV1D4UKCppWf62VE"
      #yourEndpoint填写Bucket所在地域对应的Endpoint。以华东1（杭州）为例，Endpoint填写为https://oss-cn-hangzhou.aliyuncs.com。
      endpoint: "oss-cn-shenzhen.aliyuncs.com"
      bucketname: "guli-pongluo"